# Generated by Django 3.2.8 on 2022-09-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creates',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='update',
            new_name='updated',
        ),
    ]
